/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Control.ControlChats;
import Control.ControlMensajes;
import Control.ControlRelChatsUsuarios;
import Control.ControlUsuarios;
import Enums.Sexo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import objetosNegocio.Chat;
import objetosNegocio.Mensaje;
import objetosNegocio.Usuario;

/**
 *
 * @author miran
 */
public class FrmChat extends javax.swing.JFrame {

    private Usuario usuario;
    private List<Chat> listaChats;
    private ControlRelChatsUsuarios controlRelChatsUsuarios;
    ControlUsuarios controlUsuarios;
    ControlChats controlChats;
    ControlMensajes controlMensajes;
    DefaultListModel modeloChats;
    private Chat chatSeleccionado;
    
    public FrmChat(Usuario usuario) {
        this();
        this.usuario = usuario;
        this.cambiarImagenUsuario(usuario.getSexo());
        this.cambiarNombreUsuario(usuario.getNombreUsuario());
        this.llenarListaChats();       
        this.cargarChats(); 
    }

    public FrmChat() {
        initComponents();
        this.setTitle("Frmchat");
        this.setLocationRelativeTo(this);
        TextPrompt nombreUsuario = new TextPrompt("Texto busqueda", txtBusqueda);
        TextPrompt contrasenia = new TextPrompt("Escribe un mensaje aquí", txtMensaje);
        this.controlRelChatsUsuarios = new ControlRelChatsUsuarios();
        this.controlUsuarios = new ControlUsuarios();
        this.controlMensajes= new ControlMensajes();
        this.controlChats=new ControlChats();
        this.listaChats = new ArrayList<>();
        modeloChats = new DefaultListModel();
        jListChats.setModel(modeloChats);
        this.txtAreaMensajes.setEditable(false);
        this.txtMensaje.setEditable(false);
//        this.chatSeleccionado=new Chat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoBlanco = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblEnviar = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        lblNombreChat = new javax.swing.JLabel();
        lblBuscarMensaje = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        lblActualizarMensajes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMensajes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        imgRegistrarChat = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        panelBuscar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListChats = new javax.swing.JList<>();
        lblPerfil = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        imgEditarUsuario = new javax.swing.JLabel();
        imgEditarChat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoBlanco.setBackground(new java.awt.Color(30, 169, 205));
        fondoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jPanel2.setBackground(new java.awt.Color(181, 226, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        lblEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviar32.png"))); // NOI18N
        lblEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviarMouseClicked(evt);
            }
        });

        lblNombreChat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNombreChat.setText("Nombre del chat");

        lblBuscarMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupaGris32.png"))); // NOI18N
        lblBuscarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMensajeMouseClicked(evt);
            }
        });

        lblActualizarMensajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        lblActualizarMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMensajesMouseClicked(evt);
            }
        });

        txtAreaMensajes.setColumns(20);
        txtAreaMensajes.setLineWrap(true);
        txtAreaMensajes.setRows(5);
        txtAreaMensajes.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAreaMensajes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblActualizarMensajes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEnviar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblNombreChat))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtBusqueda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblBuscarMensaje))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblNombreChat)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscarMensaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMensaje)
                        .addComponent(lblEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblActualizarMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        imgRegistrarChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chat48.png"))); // NOI18N
        imgRegistrarChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgRegistrarChatMouseClicked(evt);
            }
        });

        panelBusqueda.setBackground(new java.awt.Color(181, 226, 231));
        panelBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        panelBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refresh.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel4.setText("Chats");

        jScrollPane1.setBackground(new java.awt.Color(181, 226, 231));
        jScrollPane1.setForeground(new java.awt.Color(181, 226, 231));

        jListChats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListChatsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListChats);

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/robot48.png"))); // NOI18N

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre de Usuario");

        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logout.png"))); // NOI18N
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        imgEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editarUsuario.png"))); // NOI18N
        imgEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEditarUsuarioMouseClicked(evt);
            }
        });

        imgEditarChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editarChat.png"))); // NOI18N
        imgEditarChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEditarChatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoBlancoLayout = new javax.swing.GroupLayout(fondoBlanco);
        fondoBlanco.setLayout(fondoBlancoLayout);
        fondoBlancoLayout.setHorizontalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgEditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgRegistrarChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgEditarChat)
                .addGap(32, 32, 32)
                .addComponent(lblSalir)
                .addContainerGap())
        );
        fondoBlancoLayout.setVerticalGroup(
            fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoBlancoLayout.createSequentialGroup()
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgEditarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgRegistrarChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgEditarChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNombreUsuario)))
                .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(fondoBlancoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(fondoBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgEditarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEditarUsuarioMouseClicked
        FrmRegistrarUsuario editarUsuario = new FrmRegistrarUsuario(usuario);
        this.dispose();
        editarUsuario.cambiarLabel("Editar usuario");
        editarUsuario.setVisible(true);
    }//GEN-LAST:event_imgEditarUsuarioMouseClicked

    private void imgRegistrarChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRegistrarChatMouseClicked
        List<Usuario> usuarios = controlUsuarios.buscarTodas();
        if (usuarios.size() > 1) {
            FrmRegistrarChat registrarChat = new FrmRegistrarChat(usuario, null);
            this.dispose();
            registrarChat.cambiarLabel("Registrar cuenta");
            registrarChat.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No es posible crear un nuevo chat, debe de existir otro usuario", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_imgRegistrarChatMouseClicked

    private void imgEditarChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEditarChatMouseClicked
        if (this.chatSeleccionado!=null) {
            FrmRegistrarChat editarChat = new FrmRegistrarChat(usuario, chatSeleccionado);
            this.dispose();
            editarChat.cambiarLabel("Editar cuenta");
            editarChat.setVisible(true);
        }else{
            JOptionPane.showConfirmDialog(this,"Seleccione un chat","Aviso",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_imgEditarChatMouseClicked

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        FrmLogin login = new FrmLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void jListChatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListChatsMouseClicked
        if(evt.getClickCount()>=2){
            Chat chat= this.jListChats.getSelectedValue();    
            this.lblNombreChat.setText(chat.getNombre());
            this.cargarMensajes(chat);
        }
    }//GEN-LAST:event_jListChatsMouseClicked

    private void lblEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseClicked
        if (this.chatSeleccionado != null) {
            if (!this.txtMensaje.getText().isEmpty() && !this.txtMensaje.getText().equals("")) {
                this.enviarMensaje();
            } else {
                JOptionPane.showMessageDialog(this, "No es posible enviar un mensaje vacío", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Aún no has seleccionado un chat", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_lblEnviarMouseClicked

    private void lblActualizarMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMensajesMouseClicked
        //this.cargarMensajes(this.chatSeleccionado);   
        this.cargarMensajes(chatSeleccionado);
    }//GEN-LAST:event_lblActualizarMensajesMouseClicked

    private void lblBuscarMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMensajeMouseClicked
        // TODO add your handling code here:
        this.buscarMensajes(chatSeleccionado);
    }//GEN-LAST:event_lblBuscarMensajeMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       modeloChats.clear();
       this.llenarListaChats();
        this.cargarChats();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void llenarListaChats() {
        this.listaChats = controlRelChatsUsuarios.buscarChatsUsuario(usuario.getIdusuario());
    }

    private void cargarChats() {
        for (Chat chat : listaChats) {
            modeloChats.addElement(chat);
        }
    }
    
    private void buscarMensajes(Chat chat){
        if (chat != null) {           
            this.txtAreaMensajes.setText("");
            this.txtMensaje.setEditable(true);
            chatSeleccionado = chat;
            List<Mensaje> mensajesChat = controlMensajes.buscarComo(this.txtBusqueda.getText());
            if (!mensajesChat.isEmpty()) {
                for (Mensaje mensaje : mensajesChat) {
                    if (mensaje.getChat().equals(chatSeleccionado)) {
                        String fecha = this.cambiarFormato(mensaje.getFecha_hora());
                        String nombre;
                        if (mensaje.getUsuario().equals(this.usuario)) {
                            nombre = "Tu";
                        } else {
                            nombre = mensaje.getUsuario().getNombreUsuario();
                        }
                        String estructurado = String.format("%s:  %s  \n%s\n", nombre, mensaje.getMensaje(), fecha);
                        this.txtAreaMensajes.append(estructurado);
                    }

                }
            }
        }
    }

    private void cargarMensajes(Chat chat) {
        if (chat != null) {           
            this.txtAreaMensajes.setText("");
            this.txtMensaje.setEditable(true);
            chatSeleccionado = chat;
            List<Mensaje> mensajesChat = controlMensajes.buscarTodas();
            if (!mensajesChat.isEmpty()) {
                for (Mensaje mensaje : mensajesChat) {
                    if (mensaje.getChat().equals(chatSeleccionado)) {
                        String fecha = this.cambiarFormato(mensaje.getFecha_hora());
                        String nombre;
                        if (mensaje.getUsuario().equals(this.usuario)) {
                            nombre = "Tu";
                        } else {
                            nombre = mensaje.getUsuario().getNombreUsuario();
                        }
                        String estructurado = String.format("%s:  %s  \n%s\n", nombre, mensaje.getMensaje(), fecha);
                        this.txtAreaMensajes.append(estructurado);
                    }

                }
            }
        }
    }
    
    private void enviarMensaje(){
        if(this.chatSeleccionado!=null){
            Mensaje mensaje=new Mensaje(this.usuario,this.txtMensaje.getText(), new Date(), chatSeleccionado);
            //agregarlo al usuario también
            //chatSeleccionado.agregarMensaje(mensaje);
            if(controlMensajes.guardar(mensaje)){
                this.txtMensaje.setText("");
                this.cargarMensajes(chatSeleccionado);    
            }else{
                JOptionPane.showMessageDialog(this, "Error al enviar el mensaje");
            }
        }
        
    }
    
    private String cambiarFormato(Date date){
        String strDateFormat = "dd-MM-yyyy HH:mm"; 
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
        String fecha=objSDF.format(date);
        return fecha;
    }

    public void cambiarNombreUsuario(String texto) {
        lblNombreUsuario.setText(texto);
    }

    public void cambiarImagenUsuario(Sexo sexo) {
        if (usuario.getSexo() == Sexo.FEMENINO) {
            lblPerfil.setIcon(new ImageIcon("imagenes\\girl48.png"));
        }
        if (usuario.getSexo() == Sexo.MASCULINO) {
            lblPerfil.setIcon(new ImageIcon("imagenes\\men48.png"));
        }
        if (usuario.getSexo() == Sexo.ROBOT) {
            lblPerfil.setIcon(new ImageIcon("imagenes\\robot48.png"));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoBlanco;
    private javax.swing.JLabel imgEditarChat;
    private javax.swing.JLabel imgEditarUsuario;
    private javax.swing.JLabel imgRegistrarChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<Chat> jListChats;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActualizarMensajes;
    private javax.swing.JLabel lblBuscarMensaje;
    private javax.swing.JLabel lblEnviar;
    private javax.swing.JLabel lblNombreChat;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JTextArea txtAreaMensajes;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
